# Generated by Django 5.0.2 on 2024-02-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_raspberrypi_microservice_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberrypi',
            name='start',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='raspberrypi',
            name='id',
            field=models.TextField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
