# Generated by Django 5.0.2 on 2024-02-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_raspberrypi_microservice_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
